### PR TITLE
Prettify file and signer details

### PR DESCRIPTION
**Pull request by biern**
Copying checksum on click and displaying informative errors are in separate issues.
That information is available on hover as a title for now.

Closes: Nothing :(

### CODE REVIEW

**Comment by jksf** [comment]
I love how it looks like :+1:. One minor suggestion, external links (EtherScan, GitHub) should open in a new tab.

**Comment by jksf** [comment]
My `npm install` updated `package-lock.json` on your branch. Please check whether it's up to date.

**Comment by jksf** [comment]
I fixed external links and package-lock. Please review my changes and merge when you are ready.

**Comment by biern** [comment]
Thanks for the fix!

**Pull request merged**
