### PR TITLE
Update logo and font

### LINKED ISSUE #42: Update logo

### PR DESCRIPTION
**Pull request by biern**
Closes #42

- [x] Update logo
- [x] Update favicon

I had to cut the logo canvas manually as it was ~2x larger than the image. 
Should I:
- Create a PR with the adjusted version to replace the original logo in the graphics repo
- Create a PR and add this version with a suffix
- Do something else with it
- Do nothing with it

### CODE REVIEW

**Comment by jksf** [comment]
@biern Canvas is much larger only in `preview` builds of vector files (with background color). Use this one https://github.com/SignHash/signhash-graphics/blob/master/logomark/signhash-logomark.png (direct export with alpha channel).

I will prepare favicon.

**Comment by biern** [comment]
@jstefanski About the favicon, that's great. My ideas for that was, just cutting out the blue H, but it seems that just scaling the logo seems good enough: https://raw.githubusercontent.com/SignHash/signhash-graphics/master/logomark/signhash-logomark.png - Firefox generates a favicon on the tab here automatically, it looks good enough, we might just want to cut out all the margin to use all available space.

About the logo, I was using the svg version which has preview-like canvas size. Also I'm not 100% sure if it's a good practice to use an svg logo, but it looks quite well, and scales perfectly. 
The png version still has some margin, that would have to be reduced using css trickery.

You can find my take on cutting the logo in this PR.

**Comment by biern** [comment]
@jstefanski ok, it's done.
I've also changed the logo and content font to Roboto. Previously the logo text looked quite lousy, I think this one works quite good. I've updated the content font to match it as well.
The tests are failing now because of a typo in proof fixed in #43 that involved updating preambule in github test account.

**Comment by jksf** [comment]
I rebased it with `master` after merging #43, so it passed tests. I also updated `package-lock.json`. It had old `13.0.0` version declared not in sync with `package.json`.

**Comment by biern** [comment]
Cool, thanks

**Pull request merged**
