### PR TITLE
Mock fetching signer proofs

### PR DESCRIPTION
**Pull request by biern**
- Minimal type structure of proofs
- Fetch proofs from a mocked source

### CODE REVIEW

**Comment by jstefanski** [comment]
I cannot compile the code. Packages are installed.
```
ERROR in ./src/Main.purs
Module build failed: Error: compilation failed
    at ChildProcess.<anonymous> (/home/js/Projects/js/signhash/signhash-webapp/node_modules/purs-loader/lib/compile.js:53:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 @ ./support/entry.js 1:18-45
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./support/entry.js

ERROR in [1/2 ModuleNotFound] src/App/Hash/Types.purs:6:1

  6  import Data.Generic.Rep (class Generic)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Data.Generic.Rep was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.

[2/2 ModuleNotFound] src/App/Hash/Types.purs:7:1

  7  import Data.Generic.Rep.Show (genericShow)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Data.Generic.Rep.Show was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.

           Src   Lib   All
Warnings   0     0     0
Errors     2     0     2

webpack: Failed to compile.
```

**Review by jksf — CHANGES_REQUESTED** [review]
I cannot compile the code. Packages are installed.
```
ERROR in ./src/Main.purs
Module build failed: Error: compilation failed
    at ChildProcess.<anonymous> (/home/js/Projects/js/signhash/signhash-webapp/node_modules/purs-loader/lib/compile.js:53:18)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
 @ ./support/entry.js 1:18-45
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./support/entry.js

ERROR in [1/2 ModuleNotFound] src/App/Hash/Types.purs:6:1

  6  import Data.Generic.Rep (class Generic)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Data.Generic.Rep was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.

[2/2 ModuleNotFound] src/App/Hash/Types.purs:7:1

  7  import Data.Generic.Rep.Show (genericShow)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Data.Generic.Rep.Show was not found.
  Make sure the source file exists, and that it has been provided as an input to psc.

           Src   Lib   All
Warnings   0     0     0
Errors     2     0     2

webpack: Failed to compile.
```

**Comment by biern** [comment]
@jstefanski I made a typo during bower install and it didn't got saved, it's fixed now. About time we integrate a CI to avoid such problems

**Comment by jstefanski** [comment]
I had a problem to calculate the hash from the app (it couldn't complete). Also, the build process reported warnings. I rebased to latest `master` to see whether it builds on CI.

**Comment by jksf** [comment]
I had a problem to calculate the hash from the app (it couldn't complete). Also, the build process reported warnings. I rebased to latest `master` to see whether it builds on CI.

**Comment by jksf** [comment]
It didn't help. I'm stuck with:
```
Filename: lock.png
Size: 4687 Bytes
Loading...
No signer
```

Web console reports:
```
bundle.js:37485 [WDS] Warnings while compiling.
warnings @ bundle.js:37485
sock.onmessage @ bundle.js:59178
EventTarget.dispatchEvent @ bundle.js:36191
(anonymous) @ bundle.js:56495
SockJS._transportMessage @ bundle.js:56493
EventEmitter.emit @ bundle.js:7659
WebSocketTransport.ws.onmessage @ bundle.js:57841
bundle.js:37491            Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  

warnings @ bundle.js:37491
sock.onmessage @ bundle.js:59178
EventTarget.dispatchEvent @ bundle.js:36191
(anonymous) @ bundle.js:56495
SockJS._transportMessage @ bundle.js:56493
EventEmitter.emit @ bundle.js:7659
WebSocketTransport.ws.onmessage @ bundle.js:57841
aee6780….worker.js:716 asmCrypto seems to be load from an insecure origin; this may cause to MitM-attack vulnerability. Consider using secure transport protocol.
```

Build process output:
```
bundle.js:37485 [WDS] Warnings while compiling.
warnings @ bundle.js:37485
sock.onmessage @ bundle.js:59178
EventTarget.dispatchEvent @ bundle.js:36191
(anonymous) @ bundle.js:56495
SockJS._transportMessage @ bundle.js:56493
EventEmitter.emit @ bundle.js:7659
WebSocketTransport.ws.onmessage @ bundle.js:57841
bundle.js:37491            Src   Lib   All
Warnings   0     0     0  
Errors     0     0     0  

warnings @ bundle.js:37491
sock.onmessage @ bundle.js:59178
EventTarget.dispatchEvent @ bundle.js:36191
(anonymous) @ bundle.js:56495
SockJS._transportMessage @ bundle.js:56493
EventEmitter.emit @ bundle.js:7659
WebSocketTransport.ws.onmessage @ bundle.js:57841
aee6780….worker.js:716 asmCrypto seems to be load from an insecure origin; this may cause to MitM-attack vulnerability. Consider using secure transport protocol.
```

**Comment by biern** [comment]
@jstefanski thanks for taking the effort to test it! Turns out, I broke it while refactoring last night. Since types where checking correctly I didn't test the UI 😪 
We're going to need some kind of tests here. I don't know what type yet, probably some higher level ones since testing such a strongly typed code seems like a waste for most cases.
I've added minimal tests of what was actually failing, it probably will change a lot soon. Also CI integration is still to come.

**Pull request merged**
